# site_name: S-shifat Code Snippets Browser
site_name: sudo make s-shifat/snippets 🛠️
site_url: https://s-shifat.github.io/code-snippets/


theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.png
  # custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

extra:
  generator: false
  search:
    indexing: full  # Ensure full reindexing
  manifest: false   # Disables service worker
  social:
      - icon: fontawesome/brands/github 
        link: https://github.com/s-shifat

markdown_extensions:
  # - pymdownx.superfences  # Improves code blocks
  - pymdownx.highlight:  # Better syntax highlighting
      linenums: true  # Show line numbers
      anchor_linenums: true
      use_pygments: true
      pygments_style: dracula  # Change this for higher contrast
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite  # Inline code highlighting
  - pymdownx.snippets  # Allows reusing snippets
  - pymdownx.extra  # Extra formatting features
  - pymdownx.tilde  # Adds strikethrough support

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/search-shortcut.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.4/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.4/contrib/auto-render.min.js


plugins:
  - search  # Keeps search working
  - mkdocs-jupyter  # Enables Jupyter notebook rendering
  - exclude:
      glob:
        - "*.ju.py"  # Ignore Jupynium files


copyright: Copyright &copy; 2025 Shams-E-Shifat
